### ISSUE TITLE
Set up repository on Github

### ISSUE THREAD

**Issue by wecodewithmichaelmccloskey** [wecodewithmichaelmccloskey/Smart_Breadboard#1]
- [x] Create repository
- [x] Add collaborators
- [x] Set up Milestones
- [x] Set up Labels
- [x] Associate with Project

**Comment by creechelseaa** [comment]
Label descriptions: 

- application: Abstraction from the infrastructure code layer

- bug: Something isn't working

- circuit_card_detection: Involving the RFID reader

- debugger: Debugs the breadboard circuit

- display: Displays the information to the user 

- documentation: Improvements or additions to documentation

- duplicate: This issue or pull request already exists

- enhancement: New feature or request

- help wanted: Extra attention is needed 

- infrastructure: Involves interacting with gpio/hardware components

- invalid: Misunderstood the requirements 

- question: Further information is requested

- UI: Interacting with the user

- voltmeter_resistance_ammeter: Devices that require manual measurement from user

- wontfix: Part that will not be worked on

**Comment by Fatiha897** [comment]
@ffund Please review our project

**Comment by ffund** [comment]
:+1:
