### ISSUE TITLE
Matrix Driver Tests

### ISSUE THREAD

**Issue by Fatiha897** [wecodewithmichaelmccloskey/Smart_Breadboard#10]
Design and carry out tests to validate that the part will be suitable for the application you have planned. (Include photos/screenshots.)

**Comment by wecodewithmichaelmccloskey** [comment]
Possible tests to carry out:
- [ ] How many LEDs can be connected at once?
- [ ] How many LEDs can be on at once?
- [ ] Transition between colors (can you use a pwm signal?)

**Comment by Fatiha897** [comment]
![Matrix Driver initial test pic](https://user-images.githubusercontent.com/56314544/220725688-26953dba-2288-4b3c-bc7f-9fbfd89a95cb.jpg)

Currently, code only has 9 LEDs connected at once, can turn on 9 LEDs at once and can light up specific LEDs by passing arrays to the runLEDDebug function (see pic attached). Will attempt to expand the matrix as new parts deadline approaches, but currently there is a base to work with. Further discussion with group of it is necessary to see if color transition is necessary for the intended application of the debugger.

**Comment by wecodewithmichaelmccloskey** [comment]
@wecodewithmichaelmccloskey please review

**Comment by wecodewithmichaelmccloskey** [comment]
Looks good
