### ISSUE TITLE
Current Sensor dummy functions

### ISSUE THREAD

**Issue by creechelseaa** [wecodewithmichaelmccloskey/Smart_Breadboard#11]
This will contain the dummy functions for using the INA69 Current Sensor.

**Comment by creechelseaa** [comment]
Place in Smart_Breadboard.py:
- [ ] setup() function - if any configuration is needed, add here

- [ ] read() - returns a value 
 
These functions return pass

Call in demo.py the dumm

**Comment by wecodewithmichaelmccloskey** [comment]
I changed the semi-colons to colons on your setupCurrentSensor and readCurrentSensor functions because they were giving errors. They should be working properly now as I tested with the demo file.

**Comment by wecodewithmichaelmccloskey** [comment]
@Fatiha897 please review
