### ISSUE TITLE
Current Sensor instructions

### ISSUE THREAD

**Issue by creechelseaa** [wecodewithmichaelmccloskey/Smart_Breadboard#13]
- [x] Prepare detailed instructions for the INA69 current sensor showing how the part works and what is can do, at an expert level. 
- [x] Include photos/screenshots

**Comment by wecodewithmichaelmccloskey** [comment]
@Fatiha897 please review

**Comment by creechelseaa** [comment]
Placed into the folder labeled "instructions" in the project drive
