### ISSUE TITLE
Prepare Instructions for Touchscreen

### ISSUE THREAD

**Issue by wecodewithmichaelmccloskey** [wecodewithmichaelmccloskey/Smart_Breadboard#15]
Prepare detailed instructions showing how the part works and what is can do, at an expert level. (Include photos/screenshots).

(2 hours)

**Comment by wecodewithmichaelmccloskey** [comment]
@Fatiha897 please review

**Comment by wecodewithmichaelmccloskey** [comment]
The link to the instructions in the google drive: https://docs.google.com/document/d/1Trykh9ut0PyB_fRifjxp7gZuPvJk87z87bxcEFiesNs/edit

**Comment by Fatiha897** [comment]
T

**Comment by wecodewithmichaelmccloskey** [comment]
The "Create New Image", "Create Drawing", and "Draw Rectangle" sections are now complete:

Create New Image:
This function is complete, but it is hard to show that it is working in a standalone test. If you review the tests for any of the other display functions, you will see that they use the createNewImage() function and can verify that it works properly.

Create Drawing:
This function is complete, but it is hard to show that it is working in a standalone test. If you review the tests for any of the other display functions, you will see that they use the createDrawing() function and can verify that it works properly.

Draw Rectangle:
The draw rectangle function is used to make rectangles on the display. The rectangles can be any size, placed anywhere on the screen, and be any color.

Below is a test to verify the functionality of the function:

```
pi@raspberrypi23:~/Smart_Breadboard $ python3
Python 3.9.2 (default, Mar 12 2021, 04:06:34)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import Smart_Breadboard as sbb
>>> disp = sbb.setupDisplay()
>>> image = sbb.createNewImage(disp)
>>> draw = sbb.createDrawing(image)
>>> sbb.drawRectangle(draw, 50, 50, 380, 220, (86, 1, 141))
>>> sbb.sendToDisplay(disp, image)
>>> exit()
```
The output:


![Image](https://user-images.githubusercontent.com/114356709/230147677-310d513f-a8fa-4d50-982d-1604e54cd4ec.jpg)

**Comment by creechelseaa** [comment]
Looks good
