### ISSUE TITLE
Current Sensor Validation

### ISSUE THREAD

**Issue by creechelseaa** [wecodewithmichaelmccloskey/Smart_Breadboard#17]
- [x] Design and carry out tests to validate that the INA 169 will be suitable for the application you have planned. (Include photos/screenshots.)
- [x] conduct tests to see if current results are accurate

**Comment by wecodewithmichaelmccloskey** [comment]
Possible tests to carry out:
- [ ] Test that the input voltage matches the output voltage
- [ ] Test that the current detected is within 5% error of DMM (the range that it is accurate within)

**Comment by creechelseaa** [comment]
Using the schematic from issue #18, I used a LED circuit (red LED, 330 ohms, 3.3V power supply) to test if the current readings are accurate. I broke the circuit so VIN- is on the positive side of the terminal while VIN+ is connected to 3.3V(VCC on INA19). The current reading received was 5 mA:


![Image](https://user-images.githubusercontent.com/124189498/223670804-364429b5-aa94-44b5-85f0-48461578d077.png)

5 mA is not really an expected expected value since the percent error from the DMM current reading to the INA169 reading is 19.05%.

Current reading from DMM: 4.20 mA
% error = | (5 mA - 4.20 mA)/4.20 mA| * 100% = 19.05%

However, the percent error by hand calculations and the INA169, the reading from the sensor are  in the expected range for this LED circuit using typical red LED, 330 ohm resistor and a 3.3V power supply. Red LED's have a forward voltage rating of 1.7V , so solving for current through the LED: 

I = (3.3V - 1.7V)/330 ohms = 4.84 mA
% error = | (5 mA - 4.84 mA)/4.84 mA| * 100% = 3.31%

From the DMM, the voltage reading of the LED is about 1.6V:

![Image](https://user-images.githubusercontent.com/124189498/223675726-e545ac6e-894e-4b45-b6cd-0ea66a57508c.png)

**Comment by Fatiha897** [comment]
Test for current driver were carried out

**Comment by creechelseaa** [comment]
Add input/output readings

**Comment by wecodewithmichaelmccloskey** [comment]
@wecodewithmichaelmccloskey please review
