### ISSUE TITLE
Current Sensor PI connections

### ISSUE THREAD

**Issue by creechelseaa** [wecodewithmichaelmccloskey/Smart_Breadboard#18]
- [x] Prepare instructions (including schematic, photo, screenshots) showing how to connect the INA 169 to a Pi and validate basic I/O.

**Comment by creechelseaa** [comment]
Showing schematic of connecting the current sensor to the Pi. Vin- is left unconnected since that connection will be used for desired circuits:

[Current Sensor Connections to Pi.pdf](https://github.com/wecodewithmichaelmccloskey/Smart_Breadboard/files/10758796/Current.Sensor.Connections.to.Pi.pdf)

**Comment by wecodewithmichaelmccloskey** [comment]
@wecodewithmichaelmccloskey please review

**Comment by creechelseaa** [comment]
To connect the INA169 with the Pi, a MCP3004 will be used as an ADC between the sensor and the Pi. 

For the INA169:

- Connect VCC to the 3.3V supply 
- Connect GND to the ground rail
- Connect VIN+ to pin 2 of the potentiometer
- Connect VIN- to the ground rail
-Connect OUT to Ch0 on the MCP3004

For the potentiometer:

- Connect pin 3 to GND
- Connect pin 2 in series with a fixed resistor (I used 10k ohms) to 3.3V supply

For the MCP3004:

- Connect a wire from VCC to the 3.3V supply
- Connect AGND to the ground rail of breadboard
- Connect the DOUT pin to GPIO pin 9
- Connect the DIN pin to GPIO pin 10
- Connect the CLK pin to GPIO 11
- Connect the CS pin to GPIO 8

![INA169_MCP3004_Pi_connection](https://user-images.githubusercontent.com/124189498/221389373-0709f362-66d1-4e8f-9330-30019c0daeea.jpeg)

**Comment by wecodewithmichaelmccloskey** [comment]
This schematic looks good!

However, this schematic is for testing purposes only, as in the final product we will not be using a potentiometer to change current flow. Instead, we will be measuring the current flow from the Pi into the breadboard portion of the project, so there should be a schematic that reflects that design.

Also, since both our parts (ADC and display) use SPI we will need to discuss which CE pins on the Pi will be used for each of our parts. This may also affect how our working code functions.

**Comment by creechelseaa** [comment]
I was able to get results of the liveness of the current sensor using the testing schematic from issue #23. Since the potentiometer was used to vary the output current readings, I took out the potentiometer and labeled Vin- and Vin+ as the probes for testing desired areas in the circuits.

To connect the INA169 with the Pi, a MCP3004 will be used as an ADC between the sensor and the Pi.

For the INA169:

- Connect VCC to the 3.3V supply
- Connect GND to the ground rail
- Connect VIN+ to positive end of circuit
- Connect VIN- to the negative end of the circuit
- Connect OUT to Ch0 on the MCP3004

For the MCP3004:

- Connect a wire from VCC to the 3.3V supply
- Connect AGND to the ground rail of breadboard
- Connect DGND to the ground rail of the breadboard
- Connect the DOUT pin to GPIO pin 9
- Connect the DIN pin to GPIO pin 10
- Connect the CLK pin to GPIO 11
- Connect the CS pin to GPIO 8


[issue18LCurrToPi.pdf](https://github.com/wecodewithmichaelmccloskey/Smart_Breadboard/files/10845807/issue18LCurrToPi.pdf)

**Comment by creechelseaa** [comment]
I changed the VIN+ connection on the INA169 and updated the schematic accordingly

**Comment by wecodewithmichaelmccloskey** [comment]
Looks good
