### ISSUE TITLE
Current Sensor working code

### ISSUE THREAD

**Issue by creechelseaa** [wecodewithmichaelmccloskey/Smart_Breadboard#19]
- [x] Fill in the "dummy" functions you defined earlier with real, working code. Include instructions for testing the code by running demo.py (what should happen when you run it?)

**Comment by creechelseaa** [comment]
@wecodewithmichaelmccloskey please review

**Comment by wecodewithmichaelmccloskey** [comment]
Can you provide me with comments and pictures on what happens when you run the code?

**Comment by creechelseaa** [comment]
Add comments to code

**Comment by creechelseaa** [comment]
When I run my testing.py file that contains the current reading code, I simply receive the output from the circuit being read: 



![Image](https://user-images.githubusercontent.com/124189498/229929342-0ab8ce12-1a69-4f7e-a787-24b649871cfa.png)

**Comment by wecodewithmichaelmccloskey** [comment]
@wecodewithmichaelmccloskey please review

**Comment by wecodewithmichaelmccloskey** [comment]
@creechelseaa Can you provide me with the circuit so that I know that is what the current should be reading?

**Comment by wecodewithmichaelmccloskey** [comment]
This should not be in the Smart_Breadboard.py file:
```
setupCurrentSensor()

while True:
    current = readCurrent()
    # Print current to 3 decimal places
    print("{:.3f} A".format(current))
    time.sleep(1)
```

This should go into the demo file, and then later into the application file.

**Comment by creechelseaa** [comment]
Removed call to setupCurrentSensor() and while loop, pushed updated file

**Comment by wecodewithmichaelmccloskey** [comment]
looks good
