### ISSUE TITLE
Solder header pins to Touchscreen

### ISSUE THREAD

**Issue by wecodewithmichaelmccloskey** [wecodewithmichaelmccloskey/Smart_Breadboard#20]
All pins should be soldered to the touchscreen.

(1/2 hour)

**Comment by wecodewithmichaelmccloskey** [comment]
Soldering is finished. Images of soldered joints below.


Below (showing all pins):
![Image](https://user-images.githubusercontent.com/114356709/218282038-a51ec28a-51ba-48c0-8ae8-98475bb7a240.jpg)


Top (showing lower pins)
![Image](https://user-images.githubusercontent.com/114356709/218282050-46ab129e-695c-4bfc-9219-8eafe4ae9453.jpg)


Top (showing higher pins)
![Image](https://user-images.githubusercontent.com/114356709/218282053-71a25d7d-eefe-4e90-b5ca-64ee3da01e28.jpg)

**Comment by creechelseaa** [comment]
Cree reviewed this during team meeting.
