### ISSUE TITLE
Soldering pins to Current Sensor

### ISSUE THREAD

**Issue by creechelseaa** [wecodewithmichaelmccloskey/Smart_Breadboard#21]
Soldering header pins to the INA 169.

- [ ] 5 male header pins
- [ ]  Terminal block

**Comment by creechelseaa** [comment]
[IMG_9109.pdf](https://github.com/wecodewithmichaelmccloskey/Smart_Breadboard/files/10739346/IMG_9109.pdf)
[IMG_9110.pdf](https://github.com/wecodewithmichaelmccloskey/Smart_Breadboard/files/10739345/IMG_9110.pdf)

**Comment by creechelseaa** [comment]
Let me know if I should redo all the connections if they look too bad.

**Comment by creechelseaa** [comment]
Going to test I2C connections to make sure soldering was done correctly.

**Comment by creechelseaa** [comment]
Re-did soldering on the current sensor: looks neater.


[cuurentSensorTop.pdf](https://github.com/wecodewithmichaelmccloskey/Smart_Breadboard/files/10769318/cuurentSensorTop.pdf)

[cuurentSensorBottom.pdf](https://github.com/wecodewithmichaelmccloskey/Smart_Breadboard/files/10769320/cuurentSensorBottom.pdf)

**Comment by wecodewithmichaelmccloskey** [comment]
@wecodewithmichaelmccloskey Reviewed in class. Looks good.
