### ISSUE TITLE
Test liveness of Current Sensor

### ISSUE THREAD

**Issue by creechelseaa** [wecodewithmichaelmccloskey/Smart_Breadboard#23]
- [x] photo of actual connection to Pi

**Comment by creechelseaa** [comment]
The INA169 datasheet does _**not**_ provide any I2C connections. So I figured to run a test to determine if the current sensor works instead

**Comment by ffund** [comment]
oh you're right, it looks like it has an analog output! you should pick up an ADC in the lab.

**Comment by creechelseaa** [comment]
Connecting the current sensor to the Analog Discovery with a potentiometer to measure the OUT pin on the current sensor to see voltage output; Channel 1 on the Discovery was used to see the variation in voltage output as the potentiometer was changed:



![Image](https://user-images.githubusercontent.com/124189498/220736988-fa332156-ae8b-4b74-81fb-3a1d11c30fdf.png)

Some screenshots from the Discovery as the potentiometer is changed from pins 2 to 3:

At pin 2 of the potentiometer: 

![Image](https://user-images.githubusercontent.com/124189498/220737416-c06227e1-8b72-48be-808a-449d28cf11ca.png)

In between pins 2 and 3 of the potentiometer: 

![Image](https://user-images.githubusercontent.com/124189498/220737668-e9633644-5ff7-4190-b2f1-1759d39c35ae.png)

At pin 3 of the potentiometer: 

![Image](https://user-images.githubusercontent.com/124189498/220739687-d6f990c1-172b-4bac-9710-3e62d9368275.png)

**Comment by ffund** [comment]
Pin 2 appears to be floating in that schematic. You need to pull up to 3.3v with a fixed resistor. Then the current through the potentiometer depends on the dial setting.

I'm also not sure how to read current with this sensor - do you break the circuit, like with a multimeter? What do the examples show?

**Comment by creechelseaa** [comment]
@ffund I will make adjustments to this test as per your feedback, also current is read from Vin+ and Vin- of the INA169. From what I have been researching, those two ends work similarly to the probes of a multimeter when the current sensor is properly set up

**Comment by creechelseaa** [comment]
I redid this test but replaced the Analog Discovery with the MCP3004. The output in the terminal constantly displays 0 mA despite me turning the potentiometer. I put more details on my Pi connection in issue #18. 

![IMG_9519 Small](https://user-images.githubusercontent.com/124189498/221388281-f63e191d-622a-4a81-904e-87cfe7c20533.jpeg)

![IMG_9521 Small](https://user-images.githubusercontent.com/124189498/221388302-3ae68e3b-b0e0-40bf-b3fc-aafb073d480a.jpeg)

![IMG_9522 Small](https://user-images.githubusercontent.com/124189498/221388311-581b5906-1039-4ea6-828b-b7c9cfc9f2fd.jpeg)

![Screen Shot 2023-02-25 at 8 44 50 PM](https://user-images.githubusercontent.com/124189498/221388321-29429fdf-8543-473c-a674-6f870e05b0d6.png)

**Comment by creechelseaa** [comment]
From issue #18, I fixed the DGND connection and fixed it to my ground rail. I also connected Vin- to the ground of the potentiometer pin and was able to get current readings.

[issue23currentSens.pdf](https://github.com/wecodewithmichaelmccloskey/Smart_Breadboard/files/10845809/issue23currentSens.pdf)

**Comment by wecodewithmichaelmccloskey** [comment]
@wecodewithmichaelmccloskey please review

**Comment by creechelseaa** [comment]
From issue #17, I used the new current sensor connection shown in issue #18 to show that I received current readings other that 0 mA

**Comment by creechelseaa** [comment]
Using the schematic from issue #18, I used a LED circuit (red LED, 330 ohms, 3.3V power supply) to test if the current readings are accurate. I broke the circuit so VIN- is on the positive side of the terminal while VIN+ is connected to 3.3V(VCC on INA19). The current reading received was 5 mA:


![Image](https://user-images.githubusercontent.com/124189498/223670804-364429b5-aa94-44b5-85f0-48461578d077.png)

5 mA is not really an expected expected value since the percent error from the DMM current reading to the INA169 reading is 19.05%.

Current reading from DMM: 4.20 mA
% error = | (5 mA - 4.20 mA)/4.20 mA| * 100% = 19.05%

However, the percent error by hand calculations and the INA169, the reading from the sensor are  in the expected range for this LED circuit using typical red LED, 330 ohm resistor and a 3.3V power supply. Red LED's have a forward voltage rating of 1.7V , so solving for current through the LED: 

I = (3.3V - 1.7V)/330 ohms = 4.84 mA
% error = | (5 mA - 4.84 mA)/4.84 mA| * 100% = 3.31%

From the DMM, the voltage reading of the LED is about 1.65V:

![Image](https://user-images.githubusercontent.com/124189498/223675726-e545ac6e-894e-4b45-b6cd-0ea66a57508c.png)

**Comment by creechelseaa** [comment]
Liveness is checked by reading the output current readings; refer to issue #17

**Comment by wecodewithmichaelmccloskey** [comment]
@wecodewithmichaelmccloskey please review

**Comment by wecodewithmichaelmccloskey** [comment]
looks good
