### ISSUE TITLE
Check if Matrix Driver is Alive

### ISSUE THREAD

**Issue by Fatiha897** [wecodewithmichaelmccloskey/Smart_Breadboard#25]
Can I2C to check for the address bus

**Comment by Fatiha897** [comment]
Was able to check address for matrix driver when using i2cdatect -- received slave address 0h74, as specified on the datasheet

**Comment by wecodewithmichaelmccloskey** [comment]
@wecodewithmichaelmccloskey I reviewed in class. Looks good
