### ISSUE TITLE
Put a basic project description in the README

### ISSUE THREAD

**Issue by wecodewithmichaelmccloskey** [wecodewithmichaelmccloskey/Smart_Breadboard#3]
The project description should include

- [x] names and contact info of the team members
- [x] description of what the project does
- [x] inspiration for the project - why did we decide to do this?

**Comment by wecodewithmichaelmccloskey** [comment]
@wecodewithmichaelmccloskey please review

**Comment by wecodewithmichaelmccloskey** [comment]
The README looks good to me. The only thing we may wish to add is the user stories to the "Project Inspiration" section.

**Comment by creechelseaa** [comment]
I added the user story segment from the final report, those stories were good and if anything they can be updated.
