### ISSUE TITLE
Create a Persona for a Teenager

### ISSUE THREAD

**Issue by wecodewithmichaelmccloskey** [wecodewithmichaelmccloskey/Smart_Breadboard#30]
Create a persona to see how we believe they would interact with our product.

(2 hours)

**Comment by Fatiha897** [comment]
https://docs.google.com/document/d/1ACh-vL27uta4hAGxtSnz9i-DNX_8ruQaiqbewtIbuyY/edit?usp=sharing

Link to the shared document of personas. 
Please have personas done by Sunday night (3/25)

**Comment by creechelseaa** [comment]
@creechelseaa review

**Comment by wecodewithmichaelmccloskey** [comment]
Add homeschooled students

**Comment by creechelseaa** [comment]
Added Jim in the google document
