### ISSUE TITLE
Create a Persona for a Teacher

### ISSUE THREAD

**Issue by wecodewithmichaelmccloskey** [wecodewithmichaelmccloskey/Smart_Breadboard#31]
Create a persona to see how we believe they would interact with our product.

(1 hour)

**Comment by Fatiha897** [comment]
https://docs.google.com/document/d/1ACh-vL27uta4hAGxtSnz9i-DNX_8ruQaiqbewtIbuyY/edit?usp=sharing

Link to the shared document of personas. 
Please have personas done by Sunday night (3/25)

**Comment by creechelseaa** [comment]
@wecodewithmichaelmccloskey review

**Comment by wecodewithmichaelmccloskey** [comment]
Add more teachers with less experience and/or resources

**Comment by creechelseaa** [comment]
Added a teacher, Mrs. Johnson to the list of teachers the google document
