### ISSUE TITLE
RFID Reader Working code

### ISSUE THREAD

**Issue by wecodewithmichaelmccloskey** [wecodewithmichaelmccloskey/Smart_Breadboard#33]
- [x] Fill in the dummy functions with working code
- [x] Edit demo file to test the working code
- [ ] Verify that code works by running demo file

**Comment by Fatiha897** [comment]
I was able to get test the two functions tested by using the following section of code in a test file "RFID-test.py":


![Image](https://user-images.githubusercontent.com/56314544/227726391-67e1b893-2c74-4e91-97de-275096ac6af2.png)

The test was successful, although there were some issues with the print line spacing: 


![Image](https://user-images.githubusercontent.com/56314544/227726430-0928d802-3008-46bc-a7c0-05ee6e39d291.png)


I then tried running demo.py, but got this error when trying to run. The error appears to be on line 5 of demo.py which is an import for the Touchscreen display:


![Image](https://user-images.githubusercontent.com/56314544/227726518-e0985740-3a62-430b-8c51-6eeffb091884.png)

**Comment by creechelseaa** [comment]
@creechelseaa review

**Comment by wecodewithmichaelmccloskey** [comment]
@wecodewithmichaelmccloskey please review

**Comment by wecodewithmichaelmccloskey** [comment]
Please update the working code to use the I2C communication. See the comments in issue #34 for clarification on why.

**Comment by wecodewithmichaelmccloskey** [comment]
See #34 for clarification
