### ISSUE TITLE
Research User Stories

### ISSUE THREAD

**Issue by wecodewithmichaelmccloskey** [wecodewithmichaelmccloskey/Smart_Breadboard#36]
- [x] Find user stories of using breadboards
- [x] Find a variety of different types of people

(2 hours)

**Comment by wecodewithmichaelmccloskey** [comment]
Make sure the user stories are done by Friday night (3/24/22)

**Comment by creechelseaa** [comment]
Fictional people who could use the Smart Breadboard; 

User: Aniya
Background: Sarah is a middle school student who is learning about basic electronics in her science class. She is having difficulty understanding how to properly insert components into the breadboard and is struggling to troubleshoot issues with her circuit.

User: Selin
Background: is an adult hobbyist who enjoys building electronic projects in his spare time. She has worked with breadboards before but is having difficulty understanding how to properly use the power rails to supply power to her circuit.

User: Troy
Background: Troy is a freshman engineering student who has never worked with breadboards before. He is struggling to understand the concept of breadboards and is having a hard time following the diagrams in his textbook.

**Comment by creechelseaa** [comment]
User stories and link to post:

"I'm new to the Arduino and breadboard and I'm having a time trying to understand it. How do you wire the board?"
[https://www.reddit.com/r/arduino/comments/2x9ydj/understanding_the_breadboard/](url)

User wants to learn about the breadboard connections, says the breadboard "looks like a bunch of holes"
[https://www.reddit.com/r/raspberry_pi/comments/56zfmu/good_place_to_learn_more_about_breadboards_they/](url)

User is new to using the breadboard and seeks a "beginner friendly guide" on understanding a breadboard.
[https://www.reddit.com/r/breadboard/comments/8rcr37/new_to_breadboarding/](url)

In the comments, the first comment answers what a user finds that people "have trouble understanding" with a breadboard
[https://www.reddit.com/r/FromTheDepths/comments/lw7t8c/what_do_people_find_confusing_about_breadboards/](url)

**Comment by Fatiha897** [comment]
https://docs.google.com/document/d/1sp8OlvEzb0keUd2T94lwLiATF8wSJdZ30w_JX07L8hM/edit?usp=sharing

The link is the shared document compiling user stories

**Comment by creechelseaa** [comment]
@Fatiha897 review
