### ISSUE TITLE
Create Affinity Map

### ISSUE THREAD

**Issue by wecodewithmichaelmccloskey** [wecodewithmichaelmccloskey/Smart_Breadboard#37]
- [x] Find similarities between different people's perspectives in user stories
- [x] Create a map that has axis with the common perspectives

**Comment by wecodewithmichaelmccloskey** [comment]
Blank Affinity Map:



![Image](https://user-images.githubusercontent.com/114356709/228602821-0b60dd57-f256-41bb-bfcf-b394acf8bbbf.jpg)

**Comment by creechelseaa** [comment]
@creechelseaa review
