### ISSUE TITLE
Place Personas onto Affinity Map

### ISSUE THREAD

**Issue by wecodewithmichaelmccloskey** [wecodewithmichaelmccloskey/Smart_Breadboard#38]
- [x] Place the personas on the affinity map so that the axis correlate to different ends of each perspective

**Comment by wecodewithmichaelmccloskey** [comment]
Affinity Map with Personas placed on the map:

![Image](https://user-images.githubusercontent.com/114356709/228601903-f7ba143d-db8e-4af6-910a-d577af440758.jpg)

**Comment by creechelseaa** [comment]
@Fatiha897

**Comment by wecodewithmichaelmccloskey** [comment]
Update affinity map with new persona:



![Image](https://user-images.githubusercontent.com/114356709/230163077-feadb566-8e95-4a16-b95b-8f5a62cfe373.jpg)
