### ISSUE TITLE
Create a "stub" software library for project

### ISSUE THREAD

**Issue by wecodewithmichaelmccloskey** [wecodewithmichaelmccloskey/Smart_Breadboard#4]
- [x] Create setup file setup.py
- [x] Create library file
- [x] Test library
- [x] Update repository

**Comment by wecodewithmichaelmccloskey** [comment]
To test, I installed library with
`sudo python3 setup.py install`
with success, according to output:
`Installed /usr/local/lib/python3.9/dist-packages/Smart_Breadboard-1.0-py3.9.egg
Processing dependencies for Smart-Breadboard==1.0
Finished processing dependencies for Smart-Breadboard==1.0`
I also tested and was able to import the library and run the `info()` function without error:
`pi@raspberrypi23:~/Smart_Breadboard $ python3
Python 3.9.2 (default, Mar 12 2021, 04:06:34)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import Smart_Breadboard
>>> Smart_Breadboard.info()
Software library for the Smart Breadboard project.`

**Comment by wecodewithmichaelmccloskey** [comment]
@creechelseaa please review

**Comment by creechelseaa** [comment]
Everything looks good.
