### ISSUE TITLE
Create Sketch of Physical Design

### ISSUE THREAD

**Issue by wecodewithmichaelmccloskey** [wecodewithmichaelmccloskey/Smart_Breadboard#41]
Sketch of physical product

**Comment by creechelseaa** [comment]
One possible variation of the physical product; I tried to centralize what the user would utilize and placed the other components not being touch by the user on the outskirts: 


![Image](https://user-images.githubusercontent.com/124189498/232977424-d9716410-7155-482f-bb75-7b8434ec29d1.jpeg)

**Comment by creechelseaa** [comment]
There will be tiers to the product, the top tier will be the physical interface which has what the user will be using, the bottom tier will be the components which the user will not be using: 


![Image](https://user-images.githubusercontent.com/124189498/233138966-bdecc15a-fa31-43ce-ac11-f554d21511d3.jpg)

**Comment by creechelseaa** [comment]
Updated sketch:

![Image](https://user-images.githubusercontent.com/124189498/233157787-82762f71-942e-4b25-8bfc-9d6a9e711856.jpeg)
