### ISSUE TITLE
Matrix Driver Dummy Functions

### ISSUE THREAD

**Issue by Fatiha897** [wecodewithmichaelmccloskey/Smart_Breadboard#5]
Add "dummy" functions (that pass or return a constant value) to your library, to set up and use the basic functionality of Matrix Driver

**Comment by Fatiha897** [comment]
**Created dummy functions to begin testing the Matrix Driver:**
- def nodeToLED () #takes a "node" number on the physical circuit and returns the address of the port on the matrix driver that will be used to turn on/off the corresponding LED
- def configureCommandRegister () # configures command register in order to select for LED control register
- def turnOnLED (portAdd) # turn off LED by sending byte to port address 
- def turnOffLED (portAdd) #turn on LED by sending byte to port address

**Some issues I'm still working on with the dummy functions:** 
- For the configureCommandRegister function, I'm unsure if the frame register should select for the LED frame register or the PWM register. LED frame register is stated to "store" the current state of the LED, not necessarily alter the state of the LED. The PWM register works with "144 LEDs in 255 steps," which I think is in reference to the LED matrix that the manufacturer paired with the matrix driver. I'm trying to figure out how to adjust it for a self-made matrix grid.

**Comment by wecodewithmichaelmccloskey** [comment]
@wecodewithmichaelmccloskey please review

**Comment by wecodewithmichaelmccloskey** [comment]
Dummy functions look good. The configureCommandRegister function was not used, as you updated us that it was unnecessary and the turnOffAll and runLEDDebug are added.

Some of the spacing is different between the name of the function and the parameter list. Since Cree and I both use no spaces, I would suggest that you do the same for all of yours to keep it consistent.
