### ISSUE TITLE
Matrix Driver Instructions

### ISSUE THREAD

**Issue by Fatiha897** [wecodewithmichaelmccloskey/Smart_Breadboard#6]
Prepare instructions (including schematic, photo, screenshots) showing how to connect Matrix Driver to a Pi and validate basic I/O.

**Comment by Fatiha897** [comment]
Created a schematic for the initial LED on/off tests to with Matrix driver


[DP2 Pi, LEDs, Matrix Driver Schematic .pdf](https://github.com/wecodewithmichaelmccloskey/Smart_Breadboard/files/10745710/DP2.Pi.LEDs.Matrix.Driver.Schematic.pdf)

**Comment by wecodewithmichaelmccloskey** [comment]
@Fatiha897 please review
